---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: bggdb-deploy 
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-pod
  template:
    metadata:
      name: bggdb-pod
      labels: 
        app: bgg
        name: bggdb-pod
    spec:
      containers:
      - name: bggdb-container 
        image: stackupiss/bgg-database:v1
        ports:
        - containerPort: 3306

---
apiVersion: v1 
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec: 
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-pod
  ports:
  - port: 3306 
    targetPort: 3306