
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: codeserver-deploy 
  namespace: codeserver-ns 
  labels:
    app: codeserver
    name: codeserver-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: codeserver
      name: codeserver-pod 
  template: 
    metadata: 
      name: codeserver-pod 
      labels: 
        app: codeserver
        name: codeserver-pod 
    spec: 
      volumes:
      - name: workspace-vol
        persistentVolumeClaim:
          claimName: codeserver-pvc
      containers:
      - name: codeserver-container
        image: linuxserver/code-server:4.89.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: codeserver-cm
        - secretRef:
            name: codeserver-secret
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: workspace-vol
          mountPath: /config/workspace
          
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: codeserver-svc 
  namespace: codeserver-ns 
  labels: 
    app: codeserver 
    name: codeserver-svc 
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: codeserver-pod 
  ports:
  - port: 8443 
    targetPort: 8443

---            
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: codeserver-ing
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-ing
spec:
  ingressClassName: nginx
  rules:
  - host: codeserver-104.248.97.98.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codeserver-svc
            port:
              number: 8443

  